SYSTEM: 2.6.4 release

diff --git a/feeds/packages/net/ntpd/files/ntpd.init b/feeds/packages/net/ntpd/files/ntpd.init
--- a/feeds/packages/net/ntpd/files/ntpd.init
+++ b/feeds/packages/net/ntpd/files/ntpd.init
@@ -5,14 +5,94 @@ START=65
 STOP=65
 
 USE_PROCD=1
+PROG=/sbin/ntpd
+HOTPLUG_HELPER=/usr/sbin/ntpd.hotplug-helper
+
+config_file=/var/run/ntpd.conf
+
+trunc() {
+	echo -n "" > $config_file
+}
+
+emit() {
+	echo -e "$@" >> $config_file
+}
+
+validate_ntp_section() {
+	uci_validate_section system timeserver "${1}" \
+		'server:list(host)' 'enable:bool:1' 'enable_server:bool:0' \
+		'interface:list(string)' 'use_gps:bool:0'
+}
 
 start_service() {
-#	ln -sf /dev/ttyS0 /dev/gps0
-#	/usr/sbin/setgarmin -d /dev/gps -c /etc/setgarmin.conf
+	local server enable enable_server interface intf use_gps
+
+	validate_ntp_section ntp || {
+		echo "validation failed"
+		return 1
+	}
+
+	if [ ! -f "/usr/sbin/ntpd" ]; then
+                ln -s $PROG /usr/sbin/ntpd
+    fi
+
+
+	[ "$enable" = 0 ] && return
+
+	[ -z "$server" -a "$enable_server" = 0 ] && return
+
+	# not sure that the interfaces enumerated should be validated,
+	# since some of them might be dynamic interfaces (like IPsec
+	# tunnels) which aren't known by ubus.
+
+	trunc
+	emit "driftfile /var/lib/ntp/ntp.drift\n"
+
+	if [ "$enable_server" != 0 ]; then
+		emit "restrict default limited kod nomodify notrap nopeer"
+		emit "restrict -6 default limited kod nomodify notrap nopeer"
+	else
+		emit "restrict -4 default noserve"
+		emit "restrict -6 default noserve"
+	fi
+	emit "restrict source noquery"
+
+	emit "\n# No limits for local monitoring"
+	emit "restrict 127.0.0.1"
+	emit "restrict -6 ::1\n"
+
+	if [ -n "$interface" ]; then
+		local loopback=$(ubus call network.interface dump | jsonfilter -e "@.interface[@.interface='loopback']['device']")
+
+		local saw_lo=
+		for intf in $interface; do
+			emit "interface listen $intf"
+			[ "$intf" = "$loopback" ] && saw_lo=1
+		done
+		[ -z "$saw_lo" ] && emit "interface listen $loopback"
+		emit ""
+	fi
+
+	for i in $server
+	do
+		emit "server $i iburst"
+	done
+	if [ "$use_gps" != 0 ]; then
+		emit "server 127.127.28.0 minpoll 4 maxpoll 4 prefer"
+		emit "fudge 127.127.28.0 time1 0.35 refid GPS"
+		emit "server 127.127.22.0 minpoll 4 maxpoll 4"
+		emit "fudge 127.127.22.0 refid PPS"
+	fi
+
 	mkdir -p /var/lib/ntp
 	chown -R ntp:ntp /var/lib/ntp
 
 	procd_open_instance
-	procd_set_param command /sbin/ntpd -g -u ntp:ntp -p /var/run/ntpd.pid -n
+	procd_set_param command $PROG -g -u ntp:ntp -p /var/run/ntpd.pid -n \
+		-c $config_file
+	procd_close_instance
+
+	procd_open_instance
+	procd_set_param command $HOTPLUG_HELPER
 	procd_close_instance
 }
